version: '3.1'

services:
  auth-app:
    image: auth-test-task:1.0
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      JWT_ACCESS_SIGNING_SECRET: ${JWT_ACCESS_SIGNING_SECRET}
      JWT_REFRESH_SIGNING_SECRET: ${JWT_REFRESH_SIGNING_SECRET}
      JWT_ACCESS_TOKEN_TTL_MINUTES: ${JWT_ACCESS_TOKEN_TTL_MINUTES}
      JWT_REFRESH_TOKEN_TTL_HOURS: ${JWT_REFRESH_TOKEN_TTL_HOURS}
    depends_on:
      - db
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
      
volumes:
  postgres-data: